### ISSUE TITLE
Node.js v18 への移行

### ISSUE THREAD

**Issue by kamataryo** [geolonia/embed#348]
Mac 上で Node.js@^18 でビルドできないため

```shell
$ uname -a
Darwin Gallinago.local 20.6.0 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64 x86_64

$node -v
v18.14.1

$ yarn build
yarn run v1.22.17
$ webpack --mode production && cp ./dist/embed.js ./dist/embed && cp -r ./dist/* ./docs/
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/kamataryo/Desktop/geolonia/embed/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/Users/kamataryo/Desktop/geolonia/embed/node_modules/webpack/lib/util/createHash.js:80:21)
    at /Users/kamataryo/Desktop/geolonia/embed/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next30 (eval at create (/Users/kamataryo/Desktop/geolonia/embed/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:42:1)
    at _next8 (eval at create (/Users/kamataryo/Desktop/geolonia/embed/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/Users/kamataryo/Desktop/geolonia/embed/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:117:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/kamataryo/Desktop/geolonia/embed/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/kamataryo/Desktop/geolonia/embed/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 2.
```

**Comment by keichan34** [comment]
#402 で 20.x にアップデート
